### ISSUE TITLE
Hi!  Could you enlighten me about a pytorch problem?

### ISSUE THREAD

**Issue by BaeHann** [benearnthof/TimeGAN#3]
Hi!
  I've been confronted by a back-propagation problem of pytorch(Maybe the solution lies in the mechanism of vector to vector derivative.) 
  [](url)
  https://stackoverflow.com/questions/76021517/how-to-discern-the-computational-graph-and-the-corresponding-gradient-calculatio
 Since you're a statistician who excels in mathematics, sorry to inflict myself on you again!

**Comment by benearnthof** [comment]
Hello, I've added an answer to your question on Stackoverflow but you can also check out a short colab notebook here: 
[Link to Colab](https://colab.research.google.com/drive/1AFL-bc3-7gINxNs_ZNP3UAj0g94-2Url?usp=sharing)  
Where I look at why the values don't match. Hope that helps!

**Comment by BaeHann** [comment]
Thanks a lot! I can understand what you mean. However, in my opinion, although the value of out has been changed, the value of a and how out is calculated from a remain the same(out = a.sigmoid()), so torch.autograd.grad(out,a,weight,retain_graph=True)[0] shouldn't differ in these two programmes. For example: z = xy (x=1 and y =2, so z =2 and the derivative of z to x is 2), now I change the value of z to 0, now the derivative of z to x is still y(which still equals to 2 in this example ) . So I can hardly understand why the value of z ( the counterpart of out in these two programmes) counts.

**Comment by benearnthof** [comment]
In your first program out is equal to tensor([1., 3., 4.]).   
Performing the vector gradient then gives us the result for the function output at these values. 

In your second program you zero out c, which results in out being equal to tensor([0., 0., 0.]. 
So the last line of the second program calculates the gradient of [0, 0, 0] with respect to the inputs weighted by [1, 1, 1]
while the first program calculates the gradient of [1, 3, 4] with respect to the inputs weighted by [1, 1, 1,]

**Comment by BaeHann** [comment]
Thanks a lot!!!
